# HP discussion https://github.com/lucidrains/audiolm-pytorch/discussions/107

debug: true

model:
  codebook_size: 1024
  rq_num_quantizers: 8

trainer:
  dataset_folder: ???
  batch_size: 4
  grad_accum_every: 8
  data_max_length: 10240
  save_results_every: 1000
  save_model_every: 1000
  num_train_steps: 1_000_000
  valid_frac: 0.05

env:
  device: 0
  run_folder: ???
