# HP discussion https://github.com/lucidrains/audiolm-pytorch/discussions/107

debug: true

experiment:
  name: ???
  path_output: "results"  # ./results relative to experiment working directory
  path_checkpoints: "checkpoints"  # relative to "<path_output>/<name>/"
  path_checkpoint_sources: "source_files"  # relative to "<path_checkpoints>/"
  path_logs: "logs"  # relative to "<path_output>/<name>/"
  path_project_root: "."  # set to proper path if start from another directory
  project_checkpoint_directories:  # none of this should not be in <path_output>
    - "configs"
    - "experiments"
    - "pnc"

model:
  codebook_size: 1024
  rq_num_quantizers: 8

trainer:
  dataset_folder: ???
  batch_size: 4
  grad_accum_every: 8
  data_max_length: 10240
  save_results_every: 1000
  save_model_every: 1000
  num_train_steps: 1_000_000
  valid_frac: 0.05

env:
  device: 0
  run_folder: ???
